name: Automated QA with Playwright

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  qa_test:
    runs-on: ubuntu-latest
    name: QA Run by 22f3003023@ds.study.iitm.ac.in
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install
          npx playwright install

      - name: Run Scraper
        run: node scrape.js
